[env:m5stick-c-plus]
platform = espressif32
board = m5stick-c
framework = arduino
monitor_speed = 115200
lib_deps =
    m5stack/M5StickCPlus@^0.1.0
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.0.0
build_flags =
    -DARDUINO_M5Stick_C_Plus
